include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_CONTACT murygin280702@gmail.com)
set(CPACK_PACKAGE_VERSION_MAJOR ${SORT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${SORT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${SORT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${SORT_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION ${SORT_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "static C++ library to sort numbers")

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

set(CPACK_RPM_PACKAGE_NAME "sort-devel")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "sort")
set(CPACK_RPM_CHANGELOG_FILE ${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md)
set(CPACK_RPM_PACKAGE_RELEASE 1)

set(CPACK_DEBIAN_PACKAGE_NAME "libsort-dev")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.0")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

include(CPack)